name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          fetch-depth: 0

      - name: Add Upstream & Fetch
        run: |
          git remote add upstream https://github.com/prettier/prettier.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main || true

      - name: Cherry-pick Custom Changes
        run: |
          git fetch origin refs/heads/cherry:refs/remotes/origin/cherry
          git cherry-pick origin/cherry || true

      - name: Push Changes
        run: |
          git push origin main || true
